name: AWS OIDC Test

# on:
#   push:
#     branches: [ "main" ]

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  aws-test:
    runs-on: ubuntu-latest
    steps:
      - name: Dump OIDC token claims
        run: |
          echo "ACTIONS_ID_TOKEN_REQUEST_URL=$ACTIONS_ID_TOKEN_REQUEST_URL"
          echo "ACTIONS_ID_TOKEN_REQUEST_TOKEN=$ACTIONS_ID_TOKEN_REQUEST_TOKEN"

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{secrets.AWS_ACCOUNT_ID}}:role/github-actions-oidc
          aws-region: eu-central-1

      - name: Fetch the caller identity
        run: aws sts get-caller-identity

